name: First Workflow
on:
  push:

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello, World!"
      - name: Multiline Commands
        run: |
          node -v
          npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW version
        run: sw_vers

  dependent-job:
    needs: [run-shell-commands, parallel-job-macos]
    runs-on: windows-latest
    steps:
      - name: Final Step
        run: Write Output "Windows String"
      - name: Error Step
        run: doesnotexistsss
